# General Settings 
set -g default-terminal "screen-256color"
set -g set-titles on
set -g set-titles-string "#I:#W"
set -g mouse on # Enable mouse support

# Keymaps
unbind C-b # Default
set -g prefix C-a
bind C-a send-prefix

# Reload config
bind C-r source-file ~/.config/tmux/tmux.conf \; display "Config Reloaded"

bind '|' split-window -h 
bind -- - split-window -v 

#Taskbar
set -g status-style bg=black,fg=white
set -g status-left "#[fg=green,bold] #S "
set -g status-right "#[fg=cyan]%d %b #[fg=yellow]%H:%M "
set -g window-status-current-style fg=black,bg=cyan,bol

set -g window-status-current-format " #I:#W "

# Plugins

